---
version: '3'

services:
  ssh-bastion:
    container_name: ssh-bastion
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_PORT: 443
    image: ssh-bastion:latest
    ports:
      - 443:443
